# Generated by Django 3.0.8 on 2020-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
