# Generated by Django 3.0.8 on 2020-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session',
            new_name='watchlist',
        ),
    ]
