# Generated by Django 3.0.8 on 2020-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200821_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('TO', 'Toys'), ('PH', 'Phones'), ('ST', 'Strawberry'), ('MA', 'Mango')], max_length=2),
        ),
    ]
