# Generated by Django 3.0.8 on 2020-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200823_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('toys', 'Toys'), ('phones', 'Phones'), ('strawberry', 'Strawberry'), ('mango', 'Mango')], max_length=20),
        ),
    ]
